// Application
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const COLLAPSE_SIDEBAR = 'COLLAPSE_SIDEBAR';
export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';

// Cutscene actions
export const UPDATE_CUTSCENE = 'UPDATE_CUTSCENE';
export const ADD_CUTSCENE_ROW = 'ADD_CUTSCENE_ROW';
export const ADD_CUTSCENE_ROW_AT_POS = 'ADD_CUTSCENE_ROW_AT_POS';
export const DELETE_CUTSCENE_ROW = 'DELETE_CUTSCENE_ROW';
export const ADD_CUTSCENE_EVENT = 'ADD_CUTSCENE_EVENT';
export const EDIT_CUTSCENE_EVENT = 'EDIT_CUTSCENE_EVENT';
export const DELETE_CUTSCENE_EVENT = 'DELETE_CUTSCENE_EVENT';
export const ADD_CUTSCENE_JUMP = 'ADD_CUTSCENE_JUMP';
export const EDIT_CUTSCENE_JUMP = 'EDIT_CUTSCENE_JUMP';
export const DELETE_CUTSCENE_JUMP = 'DELETE_CUTSCENE_JUMP';
export const UPDATE_CUTSCENE_FILE_NAME = 'UPDATE_CUTSCENE_FILE_NAME';
export const UPDATE_CUTSCENE_HIDE_BARS = 'UPDATE_CUTSCENE_HIDE_BARS';

// Dialogue Actions
export const ADD_CONVERSATION = 'ADD_CONVERSATION';
export const ADD_CONVERSATION_MESSAGE = 'ADD_CONVERSATION_MESSAGE';
export const ADD_CONVERSATION_MESSAGE_AT_POS =
  'ADD_CONVERSATION_MESSAGE_AT_POS';
export const ADD_TO_CONVERSATION_MERGER = 'ADD_TO_CONVERSATION_MERGER';
export const UPDATE_DIALOGUE = 'UPDATE_DIALOGUE';
export const UPDATE_EMPTY_DIALOGUE = 'UPDATE_EMPTY_DIALOGUE';
export const UPDATE_DIALOGUE_FILENAME = 'UPDATE_DIALOGUE_FILENAME';
export const UPDATE_CONVERSATION = 'UPDATE_CONVERSATION';
export const EDIT_CONVERSATION = 'EDIT_CONVERSATION';
export const EDIT_CONVERSATION_MESSAGE = 'EDIT_CONVERSATION_MESSAGE';
export const DELETE_CONVERSATION = 'DELETE_CONVERSATION';
export const DELETE_CONVERSATION_MESSAGE = 'DELETE_CONVERSATION_MESSAGE';
export const DELETE_DIALOGUE = 'DELETE_DIALOGUE';
export const REORDER_CONVERSATION = 'REORDER_CONVERSATION';
export const REORDER_MESSAGE = 'REORDER_MESSAGE';
export const MOVE_MESSAGE = 'MOVE_MESSAGE';
export const SPLIT_CONVERSATION = 'SPLIT_CONVERSATION';
export const CONFIRM_CONVERSATION_MERGE = 'CONFIRM_CONVERSATION_MERGE';
export const DELETE_CONVERSATIONS_TO_MERGE = 'DELETE_CONVERSATIONS_TO_MERGE';
export const SELECT_ALL_CONVERSATIONS = 'SELECT_ALL_CONVERSATIONS';
export const UNSELECT_ALL_CONVERSATIONS = 'UNSELECT_ALL_CONVERSATIONS';

// Storyline Actions
export const UPDATE_STORYLINE = 'UPDATE_STORYLINE';
export const UPDATE_WITH_EMPTY_STORYLINE = 'UPDATE_WITH_EMPTY_STORYLINE';
export const UPDATE_STORYLINE_NAME = 'UPDATE_STORYLINE_NAME';
export const UPDATE_STORYLINE_APPLIES_TO_END_RUN =
  'UPDATE_STORYLINE_APPLIES_TO_END_RUN';
export const UPDATE_APPLIED_RUNS_STRING = 'UPDATE_APPLIED_RUNS_STRING';

export const ADD_STORYLINE_STEP = 'ADD_STORYLINE_STEP';
export const ADD_ENTITY_TO_NEW_MAP = 'ADD_ENTITY_TO_NEW_MAP';
export const ADD_ENTITY_TO_EXISTING_MAP = 'ADD_ENTITY_TO_EXISTING_MAP';
export const ADD_PARAM_TO_ENTITY = 'ADD_PARAM_TO_ENTITY';
export const ADD_NPC_INTERACTION = 'ADD_NPC_INTERACTION';
export const ADD_STEP_COMPLETION_BUNDLE = 'ADD_STEP_COMPLETION_BUNDLE';
export const ADD_STEP_COMPLETE_CONDITION = 'ADD_STEP_COMPLETE_CONDITION';

export const UPDATE_STEP_NAME = 'CHANGE_STEP_NAME';
export const UPDATE_MAP_ENTITY_NAME = 'UPDATE_MAP_ENTITY_NAME';
export const UPDATE_OR_ADD_MAP_ENTITY_PARAM = 'UPDATE_OR_ADD_MAP_ENTITY_PARAM';
export const UPDATE_MAP_ENTITY = 'UPDATE_MAP_ENTITY';
export const UPDATE_CONDITION = 'UPDATE_CONDITION';
export const UPDATE_BUNDLE = 'UPDATE_BUNDLE';
export const UPDATE_INTERACTION = 'UPDATE_INTERACTION';

export const DELETE_STEP = 'DELETE_STEP';
export const DELETE_MAP_ENTITY = 'DELETE_MAP_ENTITY';
export const DELETE_MAP_ENTITY_PARAM = 'DELETE_MAP_ENTITY_PARAM';
export const DELETE_NPC_INTERACTION = 'DELETE_NPC_INTERACTION';
export const DELETE_CONDITION = 'DELETE_CONDITION';
export const DELETE_BUNDLE = 'DELETE_BUNDLE';

export const CLEAR_STORYLINE = 'CLEAR_STORYLINE';
export const DUPLICATE_CONFIGURATIONS = 'DUPLICATE_CONFIGURATIONS';
