// Application
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR"

// Cutscene actions
export const UPDATE_CUTSCENE = "UPDATE_CUTSCENE"
export const ADD_CUTSCENE_ROW = "ADD_CUTSCENE_ROW"
export const DELETE_CUTSCENE_ROW = "DELETE_CUTSCENE_ROW"
export const ADD_CUTSCENE_EVENT = "ADD_CUTSCENE_EVENT"
export const EDIT_CUTSCENE_EVENT = "EDIT_CUTSCENE_EVENT"
export const DELETE_CUTSCENE_EVENT = "DELETE_CUTSCENE_EVENT"
export const ADD_CUTSCENE_JUMP = "ADD_CUTSCENE_JUMP"
export const EDIT_CUTSCENE_JUMP = "EDIT_CUTSCENE_JUMP"
export const DELETE_CUTSCENE_JUMP = "DELETE_CUTSCENE_JUMP"

